dist: bionic

sudo: false

language: node_js

node_js:
  - '13'

install:
  - npm install
  - npm run phoenix:ci 1>/dev/null
  - npm run lint
  - npm run test

jobs:
  include:
    - stage: Release
      if: branch = master AND NOT type = pull_request
      script:
        - sh .travis-release.sh
