dist: bionic

language: node_js

node_js:
  - '13'

before_install:
  - npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN

install:
  - npm install
  - npm run phoenix:ci 1>/dev/null

jobs:
  include:
    - stage: Lint & Test
      script:
        - npm run lint
        - npm run test
    - stage: Release
      if: branch = master AND NOT type = pull_request
      script:
        - sh .travis-release.sh
