dist: xenial

sudo: false

language: node_js

node_js:
  - '11'

before_install:
  - npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN

install:
  - npm install
  - npm run phoenix:ci 1>/dev/null

jobs:
  include:
    - stage: Checks
      script: npm run lint
      script: npm run test
    - stage: Release
      if: branch = master AND NOT type = pull_request
      script: sh .travis-release.sh
    - stage: Build & Deploy
      if: branch = master AND NOT type = pull_request
      script:
        - npm install now@14 -g
        - npm run build
        - now ./public -t $NOW_TOKEN
    - stage: Build & Deploy
      if: branch = master AND NOT type = pull_request
      script:
        - npm install now@14 -g
        - npm run build
        - now ./public -t $NOW_TOKEN --target production
