dist: xenial

sudo: false

language: node_js

node_js:
  - '11'

before_install:
  - npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN

install:
  - npm install
  - npm run phoenix:ci 1>/dev/null
  - npm run lint
  - npm run test

jobs:
  include:
    - stage: Deploy
      if: branch = master AND type = pull_request
      script:
        - npm install now@14 -g
        - npm run build
        - cp now.json ./public/now.json
        - now ./public -t $NOW_TOKEN
    - stage: Deploy
      if: branch = master AND NOT type = pull_request
      script:
        - npm install now@14 -g
        - npm run build
        - cp now.json ./public/now.json
        - now ./public -t $NOW_TOKEN --target production
        - sh .travis-release.sh
