import './CancelWorkTaskUseCaseSpec.js'
import './ErrorWorkTaskUseCaseSpec.js'
import './RunSimpleTaskUseCaseSpec.js'
import './RunTaskUseCaseSpec.js'
import './SetWorkPercentageTaskUseCaseSpec.js'
import './FinishWorkTaskUseCaseSpec.js'
import './ProcessQueuedTaskUseCaseSpec.js'