export const BASE_CLASS = 'sui-LoginPasswordReset'
export const EVENTS = {
  ON_RESET_PASSWORD: 'ON_RESET_PASSWORD',
  ON_CHANGE_PASSWORD: 'ON_CHANGE_PASSWORD'
}
export const STAGE_PASSWORD_RESET_START = 'STAGE_PASSWORD_RESET_START'
export const STAGE_PASSWORD_CHANGE = 'STAGE_PASSWORD_CHANGE'
export const NO_OP = () => null
