name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  check-skip:
    runs-on: ubuntu-latest
    steps:
    - name: Cancel Previous Redundant Builds
      uses: styfle/cancel-workflow-action@0.6.0
      with:
        access_token: ${{ github.token }}

  build:
    needs: check-skip
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with: 
        node-version: 16
        registry-url: 'https://registry.npmjs.org'
    - name: Install dependencies
      run: |
        npm install --legacy-peer-deps --no-audit --no-fund --no-optional
        npm run lint
        npm run build
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    - uses: actions/upload-artifact@v2
      with:
        name: public-folder
        path: public

  testing:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with: 
        node-version: 16
    - name: Install xvfb for headless testing
      run: sudo apt-get install xvfb

    - name: Setup Max User Watches for Testing
      run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

    - name: Testing
      run: |
        npm install --legacy-peer-deps --no-audit --no-fund --no-optional
        xvfb-run --auto-servernum npm run test -- --ci

  release:
    needs: [build, testing]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v2
      with: 
        node-version: 16
        registry-url: 'https://registry.npmjs.org'
    - name: Release components
      run: npx @s-ui/ci release
      env:
        GITHUB_EMAIL: cloud-accounts@scmspain.com
        GITHUB_TOKEN: ${{github.token}}
        GITHUB_USER: sui-bot
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  deploy:
    needs: [build, testing]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16
    - uses: actions/download-artifact@v2
      with:
        name: public-folder
    - name: Deploy
      run: |
        npm i -g vercel --no-save --no-fund --no-audit --no-optional --no-scripts
        DEPLOYMENT_URL=$(vercel --token $VERCEL_TOKEN --confirm $VERCEL_PARAMS)
      env:
        VERCEL_PARAMS: ${{ github.event_name != 'pull_request' && '--prod' || ''}}
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
