name: Notify on Slack about a push to master as a Ship type of change

on:
  push:
    branches:
      - 'master'

env:
  SLACK_CHANNEL_ID: C018Q6WBJ85

jobs:
  notify:
    if: ${{ github.actor != 'srv-scms-git-enb' }}
    runs-on: small
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v3
        with:
          ref: ${{ github.sha }}
      - name: Get Head Commit Message
        id: get_head_commit_message
        run: |
          echo "HEAD_COMMIT_MESSAGE=$(git show -s --format=%s)" >> "$GITHUB_ENV"
      - name: Notify
        if: ${{ contains(env.HEAD_COMMIT_MESSAGE, 'Merge pull request') == false && contains(env.HEAD_COMMIT_MESSAGE, 'skip notify') == false }}
        uses: slackapi/slack-github-action@v1
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          channel-id: ${{ env.SLACK_CHANNEL_ID }}
          payload: |
            {
            "text": ":sui: :ship: _*${{ env.HEAD_COMMIT_MESSAGE }}*_",
              "attachments": [
                {
                  "color": "#AFE1AF",
                  "blocks": [
                    {
                      "type": "context",
                      "elements": [
                        {
                          "type": "mrkdwn",
                          "text": ":point_right: ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}\n :github: <${{ github.server_url }}/${{ github.actor }}|${{ github.actor }}>"
                        }
                      ]
                    }
                  ]
                }
              ]
            }
