export const REMOTE = 'remote'
export const IN = 'IN'
export const NIN = 'NIN'
export const CHANGED = 'CHANGED'
export const EXISTS = 'EXISTS'
export const NEXISTS = 'NEXISTS'
export const RULES = 'RULES'
